version: '2.1'
networks:
  ace:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  ace-rabbitmq:
    build: ./ace-rabbitmq
    container_name: ace-rabbitmq
    env_file: ./ace.env
    hostname: ace-rabbitmq
    networks:
      ace:
        ipv4_address: 172.18.0.2
        aliases:
          - rabbitmq.ace.local
    ports: 
      - 5672:5672
      - 15672:15672
  
  ace-sql:
    build: ./ace-mssql-linux
    container_name: ace-sql
    env_file: ./ace.env
    hostname: ace-sql
    networks:
      ace:
        aliases:
          - sql.ace.local
        ipv4_address: 172.18.0.3
    ports: 
      - 1433:1433
  
  ace-app:
    build: ./ace-app
    container_name: ace-app
    env_file:
      - ./ace.env
    hostname: ace-app
    networks:
      ace:
        aliases:
          - app.ace.local
        ipv4_address: 172.18.0.4

  ace-web:
    build: ./ace-web
    container_name: ace-web
    hostname: ace-web
    networks:
      ace:
        aliases:
          - web.ace.local
        ipv4_address: 172.18.0.5
    ports:
      - "80:80"
      - "443:443"
    links:
      - ace-app